### PR TITLE
add Laravel 11 support

### PR DESCRIPTION
**Pull request by atmonshi**

### CODE REVIEW

**Comment by mokhosh** [comment]
@atmonshi I think you need to change testbench and phpunit version too.

@ryangjchandler can we show some love here please?

**Comment by ryangjchandler** [comment]
@mokhosh I'll get to this when I have time. I have seen the PR, but please do not ping or bump.

**Comment by mokhosh** [comment]
Sorry Ryan, thought it would be a simple merge. We could help if you have a list of tasks to be done.

**Comment by ryangjchandler** [comment]
@mokhosh It is a fairly simple merge, and I'll get to it when I have time. Sorry!

**Comment by bdsoha** [comment]
@ryangjchandler Laravel 11 has been officially released, any chance to get this merged?

**Pull request merged**
