### PR TITLE
Add Github Action to auto update icons

### PR DESCRIPTION
**Pull request by datlechin**
This action runs every week

### CODE REVIEW

**Comment by datlechin** [comment]
@ryangjchandler can you review this PR?

**Comment by ryangjchandler** [comment]
This is super useful, thanks. I don't think that we should be using `master` as the source for new icons though, rather the latest release.

My manual process for this is normally doing an `npm update` and running the `compile.sh` script.

**Comment by datlechin** [comment]
I updated the zip URL in the master branch to the latest release using the GitHub API to retrieve the download URL

**Comment by datlechin** [comment]
@ryangjchandler

**Pull request closed without merging**
